// <auto-generated />
namespace Ebuy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcart));
        
        string IMigrationMetadata.Id
        {
            get { return "201905200853008_added cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
